### ISSUE TITLE
Support for H6008 please

### ISSUE THREAD

**Issue by KyleSteven-sys** [Beshelmek/govee_ble_lights#54]
Can or has someone anyone able to get Govee H6008 to work? I scroll down the list but H6008 isnt in it. if someone could help that would be great!

**Comment by KyleSteven-sys** [comment]
UPDATE: so for anyone with the same issue, i found https://github.com/wez/govee-lan-hass.git and it works. you will have to have an API key which for those who dont know, you can get that API key free from Govee. In the Govee app just look for Request API key. you will then enter your email address and state your reason. i got my API key about 5 mins later but time could very. if you still have issues feel free to comment and let me know and i will try my best to help.

**Comment by gparent** [comment]
See #34

**Comment by KyleSteven-sys** [comment]
Thank you! I got it working finally lol
